### ISSUE TITLE
Rename and publish package

### ISSUE THREAD

**Issue by filips123** [godbout/dash-docset-builder#1]
PAckage is currently named `laravel-zero/laravel-zero` which is incorrect. It should be renamed to `godbout/dash-docset-builder` and published to Packagist.

This will probably allow easier usage and modifications.

**Comment by godbout** [comment]
Yeah, it's called `laravel-zero/laravel-zero` because it's built on top of `laravel-zero`. I didn't intend to publish it as a package, library, or project. I can't see the advantage compared to a git fork. I built it first for myself, and don't intend to update it as long as I can generate dash docsets. If you have any good arguments I'm open though.

**Comment by luciash** [comment]
Can be closed nowadays I guess ;)

**Comment by godbout** [comment]
still pondering... 🤔️

😂️

**Comment by godbout** [comment]
in progress...

**Comment by godbout** [comment]
@filips123 version 1.0.0 is out! README updated. you can require the composer package, and start using the bin.
